/*****************************************************************************

						ATENTION
						
   DO NOT EDIT THIS FILE. 
   THIS FILE IS AUTOMATIC GENERATED BY MARIAMOLE
   ALL CHANGES IN THIS FILE WILL BE LOST
   
   This file is used by MariaMole to work in a similar way to the original 
   Arduino IDE:
       - Automatically detect undeclared functions (Their prototypes will
	    be put here)
	   - Importing Arduino libraries (Detected .h files will be #include'd
	     here)
	   - etc

    You can disable generating this file at Preferences -> Advanced, but
	then you'll have to write your own code to import Arduino libraries
	header files and you'll have to always declare you functions 
	prototypes (which is a good practices, IMHO :) )	

*****************************************************************************/

//---------------------------------------------------------------------------
#ifndef _MARIAMOLE_AUTOMATIC_CODE_H
#define _MARIAMOLE_AUTOMATIC_CODE_H
//---------------------------------------------------------------------------

#include <Arduino.h>

/*--MARIMOLE-DEF_BEGIN--*/
void show_title(String Title);
void show_stats();
void show_solid();
void show_hum();
void show_term();
void show_time();
void loop();
void setup();
/*--MARIMOLE-DEF_END--*/

#include <HW_ARM.h>
#include <HW_ARM_defines.h>
#include <HW_AVR.h>
#include <HW_AVR_defines.h>
#include <HW_PIC32.h>
#include <HW_PIC32_defines.h>
#include <OLED_I2C.h>
#include <DS3231.h>
#include <HW_ARM.h>
#include <HW_ARM_defines.h>
#include <HW_AVR.h>
#include <HW_AVR_defines.h>
#include <HW_PIC32.h>
#include <HW_PIC32_defines.h>
#include <DHT.h>
#include <EEPROM.h>

#endif
